CREATE TABLE IF NOT EXISTS users (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  wallet_address VARCHAR(42) NOT NULL UNIQUE,
  email VARCHAR(255) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS traders (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  wallet_address VARCHAR(42) NOT NULL UNIQUE,
  experience TEXT NOT NULL,
  strategy_description TEXT NOT NULL,
  past_performance TEXT NULL,
  status ENUM('pending', 'approved', 'rejected') NOT NULL DEFAULT 'pending',
  roi_bps INT NOT NULL DEFAULT 0,
  win_rate_bps INT NOT NULL DEFAULT 0,
  drawdown_bps INT NOT NULL DEFAULT 0,
  risk_score INT NOT NULL DEFAULT 50,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS vaults (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  trader_id BIGINT UNSIGNED NOT NULL,
  contract_address VARCHAR(42) NOT NULL UNIQUE,
  asset_symbol VARCHAR(32) NOT NULL DEFAULT 'USDC',
  total_assets DECIMAL(38, 6) NOT NULL DEFAULT 0,
  total_shares DECIMAL(38, 18) NOT NULL DEFAULT 0,
  status ENUM('active', 'paused', 'closed') NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_vaults_trader FOREIGN KEY (trader_id) REFERENCES traders(id)
);

CREATE TABLE IF NOT EXISTS trades (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  vault_id BIGINT UNSIGNED NOT NULL,
  trader_id BIGINT UNSIGNED NOT NULL,
  market VARCHAR(64) NOT NULL,
  side ENUM('long', 'short') NOT NULL,
  collateral DECIMAL(38, 6) NOT NULL,
  leverage_bps INT NOT NULL,
  size_usd DECIMAL(38, 6) NOT NULL,
  pnl DECIMAL(38, 6) NULL,
  status ENUM('open', 'closed') NOT NULL DEFAULT 'open',
  tx_hash VARCHAR(66) NULL,
  opened_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  closed_at TIMESTAMP NULL,
  CONSTRAINT fk_trades_vault FOREIGN KEY (vault_id) REFERENCES vaults(id),
  CONSTRAINT fk_trades_trader FOREIGN KEY (trader_id) REFERENCES traders(id)
);

CREATE TABLE IF NOT EXISTS deposits (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NOT NULL,
  vault_id BIGINT UNSIGNED NOT NULL,
  amount DECIMAL(38, 6) NOT NULL,
  shares DECIMAL(38, 18) NOT NULL,
  tx_hash VARCHAR(66) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_deposits_user FOREIGN KEY (user_id) REFERENCES users(id),
  CONSTRAINT fk_deposits_vault FOREIGN KEY (vault_id) REFERENCES vaults(id)
);

CREATE TABLE IF NOT EXISTS withdrawals (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NOT NULL,
  vault_id BIGINT UNSIGNED NOT NULL,
  amount DECIMAL(38, 6) NOT NULL,
  shares DECIMAL(38, 18) NOT NULL,
  tx_hash VARCHAR(66) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_withdrawals_user FOREIGN KEY (user_id) REFERENCES users(id),
  CONSTRAINT fk_withdrawals_vault FOREIGN KEY (vault_id) REFERENCES vaults(id)
);
